# Chapter 2: Statistical Learning
## End of chapter lab

### 2.3.2 Basic Commands

Like most programming languages, Python uses functions to perform op- erations. To run a function called fun, we type fun(input1,input2), where the inputs (or arguments) input1 and input2 tell Python how to run the function. A function can have any number of inputs. For example, the print() function outputs a text representation of all of its arguments to the console.

In [1]:
print("fit a model", 11, "variables")

fit a model 11 variables



The following command will provide information about the print() function.

In [2]:
print?

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method

Adding two integers in Python is pretty intuitive.


In [3]:
3 + 5

8

In Python, textual data is handled using strings. For instance, "hello" and 'hello' are strings. We can concatenate them using the addition + symbol.

In [4]:
"hello" + " " + "world"

'hello world'

A string is actually a type of *sequence*: this is a generic term for an ordered list. The three most important types of sequences are lists, tuples, and strings. We introduce lists now.
The following command instructs Python to join together the numbers 3, 4, and 5, and to save them as a list named x. When we type x, it gives us back the list.


In [5]:
x = [3,4,5]
x

[3, 4, 5]

Note that we used the brackets [] to construct this list. 

We will often want to add two sets of numbers together. It is reasonable to try the following code, *though it will not produce the desired results*.

In [6]:
y = [4,9,7]
x + y

[3, 4, 5, 4, 9, 7]

Why did python not add the entries of the lists element-by-elemnt. In Python, lists hold *arbitrary* objects, and are added using *concatenation*. This is the same behavior as when we added "hello" + " " + "world".

This example reflects the fact htat Python is a *general-purpose* programming language. Much of Python's **data-specific** functionality comes from other packages, notably `numpy` and `pandas`. 

### 2.3.3 Introduction to Numerical Python

We need the `numpy` library to perform the lessons in this book. A library (or package) is a collection of modules that are not necessarily included in the base Python distribution.

To access `numpy` we must first **import it**

In [7]:
import numpy as np

In the above line, we named the `numpy` module `np` for ease of referencing. 

In `numpy`, an *array* is a generic term for a multidimensional set of numbers. We use the `np.array()` funciton to define x and y, which are one-dimensional arrays --> vectors. 

In [9]:
x = np.array([3,4,5])
y = np.array([4,9,7])

If you forget to run the `import numpy as np` command *before* any cells that use `numpy` functionalities, you will get an error. The syntax `np.array()` indicates that the function being called is part of the `numpy` package.

Since x and y have been defined using `np.array()`, we can now add them together as vectors.

In [10]:
x + y

array([ 7, 13, 12])

In `numpy`, matrices are typically represented as *two-dimensional arrays*, and vectors as *one-dimensional arrays*. Let's create a two-dimensional array below. 

In [14]:
x = np.array([[1,2], [3,4]])
x

array([[1, 2],
       [3, 4]])

*Can also create matrices using `np.matrix()`*

The object x has several *attributes*, or associated objects. to access an attribute of x, we type `x.attribute` where replace attribtue with the name of hte attribute. For example, we can access the ndim attribute of x below. 

In [13]:
x.ndim

2

The output tells us that x is a 2D array. Similarly, `x.dtype` is the *data type* attribute of the object x. This indicates that x is comprised of 64-bit integers. 

In [15]:
x.dtype

dtype('int64')

Why is x made up of integers? This is because we made x by passing in only integers to the np.array() function. If we had passed in any decimals, then we would have obtained an arary of *floating point numbers* (real-valued numbers).

In [17]:
np.array([[1,2], [3.0,4]]).dtype

dtype('float64')

Typing `fun?` will prompt Python to displayy the documentation associated with the function, fun.

In [19]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

The documentation tells us that we can manually set the dtype for our arrays.

In [21]:
np.array([[1,2], [3,4]], dtype=float).dtype

dtype('float64')

The array x is 2D. We can find the number of rows and columns by using the `shape` attribute.

In [22]:
x.shape

(2, 2)

A *method* is a function that is associated *with an object*. For example, given an array x, the expression `x.sum()` will sum all of its elements using the `sum()` method for arrays. The call `x.sum()` automatically provides x as the first argument to its `sum()` mehtod. 

In [23]:
x = np.array([1,2,3,4])
x.sum()

10

We could also sum the elements of x by passing in x as an *argument* to the np.sum() function. 

In [24]:
x = np.array([1,2,3,4])
np.sum(x)

10

The reshape() method return a new arary with the same elemnts as x, but a different shape. We do this by passing in a **tuple** in our call to reshape(), in this case (2,3)

This tuple specifies that we would like to create a 2D array with 2 rows and 3 columns.

In [25]:
x = np.array([1,2,3,4,5,6])
print("beginning x:\n", x)
x_reshape = x.reshape((2,3))
print("reshaped x:\n", x_reshape)

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


The above output tells us that numpy arrays are specific as a sequence of *rows*. This is called *row-major ordering*, as opposed to *column-major ordering*. 

Python uses 0-based indexing. this means that to access the top left elemnt of x_reshape, we type in x_reshape[0,0]. 

In [26]:
x_reshape[0,0]

1

x_reshape[1,2] will show the element in the second row and third column of the array. 

In [27]:
x_reshape[1,2]

6

x[2] will show the **third** entry of x.

Let's modify the top left elemnt of x_reshape. To our surprise, we find that the 1st element of x has been changed as well.

In [28]:
print("x before we modify x_reshape:\n", x)
print("x before we modify x_reshape:\n", x_reshape)
x_reshape[0,0] = 5
print("x_reshape after we modify its top left element:\n",
      x_reshape)
print("x after we modify its top left element:\n",
      x)


x before we modify x_reshape:
 [1 2 3 4 5 6]
x before we modify x_reshape:
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify its top left element:
 [[5 2 3]
 [4 5 6]]
x after we modify its top left element:
 [5 2 3 4 5 6]


Changing x_reshape also changes x because the two objects occupy the same space in memory .

We saw that we can modify an individual element in an array. Can we modify a tuple? **We cannot** -- trying to do so causes an error.

In [29]:
my_tuple = (3,4,5)
my_tuple[0] = 2

TypeError: 'tuple' object does not support item assignment

Below are some useful attribute of arrays. 

Shape contains its dimensions as a tuple.

ndim shows the number of dimensions

T provides its transpose

In [30]:
x_reshape.shape, x_reshape.ndim, x_reshape.T

((2, 3),
 2,
 array([[5, 4],
        [2, 5],
        [3, 6]]))

Notice that the outputs are output as tuples.

We will often want to apply function sto arrays. For instance we can find the square root of the entries using np.sqrt():

In [31]:
np.sqrt(x)

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

We can also square them:

In [32]:
x**2

array([25,  4,  9, 16, 25, 36])

We can compute the square roots with the same notation by raising to the 1/2 power.

In [33]:
x**0.5

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

To generate random normal variables, we use the np.random.normal() function. The first line of the help page reads normal(loc=0.0, scale=1.0, size=None). This signature line tells us that the function’s arguments are loc, scale, and size. These are keyword arguments, which means that when they are passed into the function, they can be referred to by name (in any order). By default, this function will generate random normal variable(s) with mean (loc) 0 and standard deviation (scale) 1; furthermore, a single random variable will be generated unless the argument to size is changed.
We now generate 50 independent random variables from a N(0,1) distribution.

In [35]:
x = np.random.normal(size=50)
x

array([-1.41374796,  0.29492268,  1.22654286, -0.05606457,  0.91745601,
        0.82974361, -0.09649339,  0.74284519,  0.13030655, -1.53364888,
       -0.0752243 ,  0.33853812, -1.08264913,  0.40094918,  0.0438562 ,
        0.4614146 ,  1.15039416,  0.23344109,  0.51112801,  0.06717158,
       -0.32866126,  1.9899385 , -0.86807977, -0.30642867, -0.72299399,
       -0.19327252, -0.70661492, -0.39596044,  0.96654694, -0.60120003,
       -0.45193673, -0.87954921, -1.4289223 , -0.16840386,  0.60035454,
        0.2903849 , -1.33334829, -1.2273144 ,  0.67556046, -1.71740682,
       -0.30082275,  0.99319421, -0.02370067, -1.38130605, -0.85003025,
        0.06894147, -0.04174688,  0.45081402, -0.8320434 ,  0.80051369])

We create an array y by adding an independent N(50,1) random variable to each element of x.

In [36]:
y = x + np.random.normal(loc=50, scale=1, size=50)

We create an array y by adding an independent N(50,1) random variable to each element of x.
y. The off-diagonal elements give the correlation between x and y.

In [37]:
np.corrcoef(x,y)

array([[1.        , 0.59814644],
       [0.59814644, 1.        ]])

You probably noticed that you got a different set of results when you ran the past few commands. In particular, each time we call np.random.normal(), we will get a different answer, as shown in the following example.

In [39]:
print(np.random.normal(scale=5, size=2)) 
print(np.random.normal(scale=5, size=2))

[0.8064091  3.10324658]
[-1.7490621   1.02248799]


To make sure our code is reproducible, we can set a *random seed* using the np.random.default_rng() function. This takes a an arbitrary, user-specified integer arg. If we set a random seed before generating ranodm data, the re-running our code will yield the same results. The obj rng essentially has all the random numebr genreating methods found in np.random. Hence, to generate normal data, we use rng.normal(). 

In [40]:
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]


The np.mean(), np.var(), and np.std() functions can be used to find the mean, variance, and standard deviation of arrays. They are also available as methods on arrays.

In [42]:
rng = np.random.default_rng(3)
y = rng.standard_normal(10)
np.mean(y), y.mean()

(-0.1126795190952861, -0.1126795190952861)

In [43]:
np.var(y), y.var(), np.mean((y-y.mean())**2)

(2.7243406406465125, 2.7243406406465125, 2.7243406406465125)

Notice that by default np.var() divides by the sample size n rather than
n − 1; see the ddof argument in np.var?.

In [44]:
np.sqrt(np.var(y)), np.std(y)

(1.6505576756498128, 1.6505576756498128)

The np.mean(), np.var(), and np.std() functions can also be applied to the rows and columns of a matrix. To see this, we construct a 10 × 3 matrix of N(0,1) random variables, and consider computing its row sums.

In [45]:
X = rng.standard_normal((10, 3))
X

array([[ 0.22578661, -0.35263079, -0.28128742],
       [-0.66804635, -1.05515055, -0.39080098],
       [ 0.48194539, -0.23855361,  0.9577587 ],
       [-0.19980213,  0.02425957,  1.54582085],
       [ 0.54510552, -0.50522874, -0.18283897],
       [ 0.54052513,  1.93508803, -0.26962033],
       [-0.24355868,  1.0023136 , -0.88645994],
       [-0.29172023,  0.88253897,  0.58035002],
       [ 0.0915167 ,  0.67010435, -2.82816231],
       [ 1.02130682, -0.95964476, -1.66861984]])

Since arrays are *row-major ordered*, the first axis --> axis =0, refers to its rows. We pass this arg into the mean() method for X.

In [46]:
X.mean(axis=0)

array([ 0.15030588,  0.14030961, -0.34238602])

In [47]:
X.mean(0)

array([ 0.15030588,  0.14030961, -0.34238602])

### 2.3.4 Graphics